### Import Dependencies

In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../Dataset/COVID-data.csv')

# We will consider cases for INDIA only
df = df[df.location == 'India'].reset_index()
df.head()

,index,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,24008,IND,Asia,India,2020-01-30,1.0,1.0,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
1,24009,IND,Asia,India,2020-01-31,1.0,0.0,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
2,24010,IND,Asia,India,2020-02-01,1.0,0.0,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
3,24011,IND,Asia,India,2020-02-02,2.0,1.0,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64
4,24012,IND,Asia,India,2020-02-03,3.0,1.0,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64

In [3]:
df.columns

Index(['index', 'iso_code', 'continent', 'location', 'date', 'total_cases',
       'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'new_vaccinations', 'total_vaccinations_per_hundred',
       'new_vaccinations_per_million', 'stringency_index', 'population',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index'],
      dtype='object')

In [4]:
drop_col = ['index', 'iso_code', 'continent', 'location', 'reproduction_rate',
            'stringency_index', 'population','population_density', 'gdp_per_capita', 
            'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 
            'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
            'life_expectancy', 'human_development_index']

df = df.drop(drop_col, axis=1)
df.head()

,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,...,positive_rate,tests_per_case,tests_units,total_vaccinations,new_vaccinations,total_vaccinations_per_hundred,new_vaccinations_per_million,median_age,aged_65_older,aged_70_older
0,2020-01-30,1.0,1.0,NaN,NaN,NaN,NaN,0.001,0.001,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.2,5.989,3.414
1,2020-01-31,1.0,0.0,NaN,NaN,NaN,NaN,0.001,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.2,5.989,3.414
2,2020-02-01,1.0,0.0,NaN,NaN,NaN,NaN,0.001,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.2,5.989,3.414
3,2020-02-02,2.0,1.0,NaN,NaN,NaN,NaN,0.001,0.001,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.2,5.989,3.414
4,2020-02-03,3.0,1.0,NaN,NaN,NaN,NaN,0.002,0.001,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.2,5.989,3.414

In [5]:
#save dataset
df.to_csv('../Dataset/India.csv',index=False)